"""Rebuild every generated document from data/scenario.yaml.

Writes:
    docs/figures/*.png         charts used in the README
    docs/results.md            ranking, workings, sensitivity and downside tables
    docs/one_page_summary.pdf  consulting-style executive summary

Run with ``make report`` or ``python scripts/build_report.py``.
"""

from __future__ import annotations

import textwrap
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

from rtm import charts, fmt
from rtm.config import load_scenario
from rtm.finance import run_financials
from rtm.recommend import build_recommendation
from rtm.scoring import score_routes, summary_table
from rtm.sensitivity import downside_table, tornado, weight_flips, weight_map, weight_sweep

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
FIGURES = DOCS / "figures"
A4_LANDSCAPE = (11.69, 8.27)


def md_table(df: pd.DataFrame) -> str:
    """Minimal Markdown table (avoids an extra dependency)."""
    header = "| " + " | ".join(str(c) for c in df.columns) + " |"
    rule = "|" + "|".join("---" for _ in df.columns) + "|"
    rows = ["| " + " | ".join(str(v) for v in row) + " |" for row in df.itertuples(index=False)]
    return "\n".join([header, rule, *rows])


def save_figures(s, fin, result, sweep, table, grid) -> None:
    FIGURES.mkdir(parents=True, exist_ok=True)
    charts.key_chart(s, result, fin).savefig(FIGURES / "key_chart.png")

    fig, axes = plt.subplots(1, 3, figsize=(11, 3.4), sharey=True)
    charts.plot_weight_sweep(list(axes), s, result, sweep)
    fig.tight_layout()
    fig.savefig(FIGURES / "weight_sweep.png")

    fig, ax = plt.subplots(figsize=(8.5, 4.6))
    charts.plot_tornado(ax, s, table)
    fig.savefig(FIGURES / "tornado.png")

    fig, ax = plt.subplots(figsize=(6.5, 5.2))
    charts.plot_weight_map(ax, s, result, grid)
    fig.savefig(FIGURES / "weight_map.png")

    fig, ax = plt.subplots(figsize=(8, 3.8))
    charts.plot_cash(ax, s, fin, downside=True)
    fig.savefig(FIGURES / "cash_downside.png")
    plt.close("all")


def write_results(s, result, rec, table, flips, down) -> None:
    summary = summary_table(s, result).round(1)
    workings = result.workings.assign(
        route=lambda d: d.route.map(s.label), value=lambda d: d.value.round(3)
    ).round(2)
    torn = (
        table.head(10)
        .assign(
            base_value=lambda d: [
                fmt.money(v, s.currency) if v >= 1000 else round(v, 2) for v in d.base_value
            ],
            winner_low=lambda d: d.winner_low.map(s.label),
            winner_high=lambda d: d.winner_high.map(s.label),
        )[["label", "base_value", "lead_low", "lead_high", "winner_low", "winner_high"]]
        .round(1)
    )
    flips = flips.assign(new_winner=lambda d: d.new_winner.map(s.label)).round(3)
    down = down.assign(
        route=lambda d: d.route.map(s.label),
        revenue_base=lambda d: [fmt.money(v, s.currency) for v in d.revenue_base],
        revenue_downside=lambda d: [fmt.money(v, s.currency) for v in d.revenue_downside],
        peak_funding_base=lambda d: [fmt.money(v, s.currency) for v in d.peak_funding_base],
        peak_funding_downside=lambda d: [fmt.money(v, s.currency) for v in d.peak_funding_downside],
    ).round(2)
    text = f"""# Results

Generated by `scripts/build_report.py` from `data/scenario.yaml`. Do not edit by hand.

Scenario: {s.name}. Weights: {", ".join(f"{k} {fmt.pct(v)}" for k, v in result.weights.items())}.

## Ranking

{md_table(summary)}

## Recommendation

{rec.to_markdown()}

## Weight flips

Nearest weight, above or below the default, at which the top route changes (the other
two weights keep their default ratio).

{md_table(flips)}

## Tornado: top 10 inputs

Winner's lead over the next-best route (points) with each input moved -/+
{fmt.pct(s.sensitivity.tornado_swing)}. Base lead: {table.attrs["base_lead"]:.1f} points.

{md_table(torn)}

## Downside case

Breakeven months above {s.horizon_months} are projected past the horizon.

{md_table(down)}

## Scoring workings

{md_table(workings)}
"""
    (DOCS / "results.md").write_text(text, encoding="utf-8")


def _wrap(text: str, width: int) -> str:
    return "\n".join(textwrap.wrap(text, width))


def one_page_pdf(s, fin, result, rec) -> None:
    """A4 landscape executive summary: headline, three points, evidence, risks, next steps."""
    fig = plt.figure(figsize=A4_LANDSCAPE)
    ink, ink2, accent = charts.INK, charts.INK_2, charts.DIMENSION_SHADES["velocity"]

    fig.text(
        0.04, 0.955, "ROUTE-TO-MARKET RECOMMENDATION", color=accent, fontsize=9, fontweight="bold"
    )
    fig.text(
        0.04,
        0.935,
        _wrap(rec.headline, 95),
        color=ink,
        fontsize=15,
        fontweight="bold",
        va="top",
        linespacing=1.3,
    )
    fig.text(
        0.04,
        0.845,
        f"{s.name}. Three routes scored on Velocity, Margin and Robustness "
        f"over {s.horizon_months} months. All data synthetic.",
        color=ink2,
        fontsize=9,
    )

    # Left column: the three supporting points.
    y = 0.79
    fig.text(0.04, y, "Why", color=accent, fontsize=10, fontweight="bold")
    y -= 0.035
    for i, point in enumerate(rec.why, 1):
        fig.text(0.04, y, f"{i}", color=accent, fontsize=16, fontweight="bold", va="top")
        body = _wrap(point, 62)
        fig.text(0.07, y, body, color=ink, fontsize=9.5, va="top", linespacing=1.35)
        y -= 0.03 + 0.024 * body.count("\n") + 0.03

    # Right column: the evidence.
    ax1 = fig.add_axes((0.53, 0.52, 0.2, 0.26))
    charts.plot_scores(ax1, s, result)
    ax1.legend(loc="upper center", bbox_to_anchor=(0.5, -0.1), ncol=3, fontsize=6)
    ax1.set_xlabel("")
    ax2 = fig.add_axes((0.79, 0.52, 0.18, 0.26))
    charts.plot_cash(ax2, s, fin)
    ax2.set_title("Cumulative cash")
    ax2.legend(fontsize=6, loc="lower left")
    for ax in (ax1, ax2):
        ax.tick_params(labelsize=7)
        ax.title.set_fontsize(9)

    # Bottom band: when it stops winning, risks, next steps.
    fig.add_artist(plt.Line2D([0.04, 0.96], [0.42, 0.42], color=charts.GRID, linewidth=1))
    columns = (
        ("It stops winning if", rec.stops_winning[:4]),
        ("Top three risks", rec.risks),
        ("Next steps", rec.next_steps),
    )
    for col, (title, items) in enumerate(columns):
        x, y = 0.04 + col * 0.315, 0.395
        fig.text(x, y, title, color=accent, fontsize=10, fontweight="bold", va="top")
        y -= 0.04
        for i, item in enumerate(items, 1):
            body = _wrap(item, 52)
            fig.text(x, y, f"{i}.", color=ink2, fontsize=8.5, va="top")
            fig.text(x + 0.018, y, body, color=ink, fontsize=8.5, va="top", linespacing=1.3)
            y -= 0.022 * (body.count("\n") + 1) + 0.014

    fig.text(
        0.04,
        0.025,
        "Method: each metric scaled 0-100 between fixed anchors, averaged "
        "within each dimension, then weighted. All assumptions and their sources are in "
        "data/scenario.yaml; formulas in docs/methodology.md.",
        color=ink2,
        fontsize=7,
    )
    with plt.rc_context({"savefig.bbox": "standard"}):  # keep the full A4 page
        fig.savefig(DOCS / "one_page_summary.pdf")
    plt.close(fig)


def main() -> None:
    s = load_scenario()
    fin = run_financials(s)
    result = score_routes(s, fin)
    rec = build_recommendation(s)
    table = tornado(s)
    save_figures(s, fin, result, weight_sweep(s, result), table, weight_map(s, result))
    write_results(s, result, rec, table, weight_flips(s, result), downside_table(s))
    one_page_pdf(s, fin, result, rec)
    print(f"Wrote figures, results.md and one_page_summary.pdf to {DOCS}")


if __name__ == "__main__":
    main()
